# Generated by Django 4.2.10 on 2024-04-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("miapp", "0002_alter_pokemon_id_pokemon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="experiencia",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pokemon", name="peso", field=models.CharField(max_length=50),
        ),
    ]
